# Generated by vcd_resource_list - 2024-08-07T12:53:35+02:00
# Import directive for vcd_vapp_vm abarreiro.vdc-abarreiro.TestVapp.TestVm 
import {
  to = vcd_vapp_vm.TestVm-e9e59642512c
  id = "abarreiro.vdc-abarreiro.TestVapp.TestVm"
}

