# Generated by vcd_resource_list - 2024-08-07T12:53:34+02:00
# Import directive for vcd_vm abarreiro.nsxt-vdc-abarreiro.ldap-server 
import {
  to = vcd_vm.ldap-server-8d3b281e57cd
  id = "abarreiro.nsxt-vdc-abarreiro.urn:vcloud:vm:8d38b523-bfdc-4b49-b548-8d3b281e57cd"
}

